#######################################
# Sam Gartrell
# 20250109
# automated image ID
# NOTE: inaturalist App guidelines mandate that "content must be generated with real human involvement or oversight"
# This app therefore only creates a CSV of image IDs designed for manual review before uploading to iNaturalist
#######################################
import sys
import os
import json
import requests
import PIL
import datetime


def refresh_token(
    manual_token="eyJhbGciOiJIUzUxMiJ9.eyJ1c2VyX2lkIjo4ODA4MjMzLCJleHAiOjE3MzY1NDU1NTR9.L2OXIr6gS8wELPUA1pmm7ZIyGNzhUWLvlKFEIWPhhhAac0MbQHo6FA-gupaJY-XuZoAd5IOfyhrNhitICW1dvw",
):
    print(f"getting token...")
    # TODO: need an oauth app setup, request one here: https://www.inaturalist.org/oauth/app_owner_application
    # in interim, tokens can be generated by manually visting the endpoint in browser after authenticating, and tokens last 2 months or something crazy
    res = requests.get("https://www.inaturalist.org/users/api_token?f=json")
    if res and res.ok:
        try:
            token = res.json().get("api_token", ValueError("Failed to get token"))
            return token
        except Exception as e:
            print(e)
    return manual_token


def get_cv_ids(image_path):
    # assemble payload with jpeg bytes like
    # -----------------------------110819625921283343413685461672
    # Content-Disposition: form-data; name="image"; filename="blob"
    # Content-Type: image/jpeg
    # <jpeg bytes>
    # -----------------------------110819625921283343413685461672--
    with open(image_path, "rb") as image_file:
        files = {"image": image_file}
        headers = {"Authorization": refresh_token()}
        res = requests.post(
            "https://api.inaturalist.org/v1/computervision/score_image",
            files=files,
            headers=headers,
        )
    print(json.loads(res.text))
    return json.loads(res.text)


res = get_cv_ids(
    r"F:\SGP\repos\inat-upload-utils\batch_upload\images\gfhd32343j43334.jpg"
)
print(res)
